### PR TITLE
remove nameko service

### PR DESCRIPTION
**Pull request by rowan08**
Remove nameko code from the metrics-api. Posting data from the `altmetircs` service will just be done with API calls.

### CODE REVIEW

**Review by fradeve — APPROVED** [review]

**Comment by ja573** [comment]
Can we not simply toggle the use of nameko with an env variable? And remove mentions to the altmetrics service to allowing requests via both http and amqp

**Comment by ja573** [comment]
Or we could do a separate repo with nameko's configuration and then run the container mapping the source of the api as a volume to nameko config's

**Comment by fradeve** [comment]
> Or we could do a separate repo with nameko's configuration and then run the container mapping the source of the api as a volume to nameko config's

In order to keep the project clean, I'd really like to avoid:
* keeping code that we don't use (either in `master`, a different branch or a different repository)
* keeping configuration that we don't use

Toggling the usage of Nameko with and env variable is a sensible suggestion, but that would imply that we allow inter-service communication to happen in different ways, which I'd really like to avoid as well.

We are happy to remove Nameko following your feedback.

**Comment by ja573** [comment]
Yes, those were indeed my concerns. Now I was simply suggesting to explore other possibilities before simply getting rid of it amqp, if having it is useful at all - but fair enough, let's just remove it

**Review by ja573 — APPROVED** [review]

**Pull request merged**
